src/home-made-meal/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#hero'
  get '/home/show/:id', to: 'home#show', as: 'show'
  get '/home/index', to: 'home#index', as: 'index'
  get '/home/about', to: 'home#about', as: 'about'
  get '/home/admin', to: 'home#admin', as: 'admin'
  devise_scope :user do
    get "/login", :to => "devise/sessions#new" # Add a custom sign in route for user sign in
    delete "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
    get "/sign_up", :to => "devise/registrations#new" # Add a Custom Route for Registrations
    devise_for :user
  end
  resources :profiles 
  resources :food_items do
    resources :comments
  end
  resources :line_items
  resources :carts
  resources :reviews
  post "payment/index", to: "payment#create", as: "payment"
  get 'payment/cancel', to: 'payment#cancel', as: 'payment_cancel'
  get 'payment/success', to: 'payment#success', as: 'payment_success'
end

src/home-made-meal/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  # the add_food_item method will check if the list of items already includes the item we adding, if it does it will show the quantity and if it doesn't it will build a new line items for the user 
  def add_food_item(food_item)
    current_item = line_items.find_by(food_item_id: food_item.id)
      if current_item
        # I couldn't do increment by adding current_item.quantity += 1, for "+" it would return an error for undifined method for "+", I used increment bulit in method from ruby and it workd fine
        current_item.increment!(:quantity)
      else
        current_item = line_items.build(food_item_id: food_item.id)
      end
    current_item
  end
  # we get the total price of the all the item inside the line iems 
  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

src/home-made-meal/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  rescue_from  ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :disable_footer, only:[:show]
  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil 
    respond_to do |format|
      format.html { redirect_to index_url, notice: "Your cart is currently empty" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path
    end
    def disable_footer
      @disable_footer = true
    end
end

src/home-made-meal/app/helpers/carts_helper.rb
module CartsHelper
end

src/home-made-meal/app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
   <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
<% end %>

src/home-made-meal/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

src/home-made-meal/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
 <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

src/home-made-meal/app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

src/home-made-meal/app/views/carts/show.html.erb
<section class="p-5">
  <div class="container">
  
    <% @cart.line_items.each do |item| %>
      <div class="row align-items-center justify-content-center">
        <div class="col">
          <% if item.food_item.images.attached? %>
            <%= image_tag item.food_item.images.first, class: "cart-show-image"%>
          <% end %>
        </div>
        <div class="col">
          <h3><%= item.food_item.name %></h3>
        </div>
        <div class="col">
          <p><%= number_to_currency(item.total_price) %></p>
        </div>
        <div class="col">
          <p><%= item.quantity %></p>
        </div>
        <div class="col">
          <p><%= button_to "Remove item", item, class: "btn btn-danger", method: :delete %></p>
        </div>
      </div>
      <hr>
      <%# capturing the food_item.id and pass it to the payment_path as a argument for food id, than I can create a buyer id once the checkout is successful, I'm not sure if it's the right way to do this, but if I would use my checkout link inside @cart.line_items.each block it would create the checkout button for each food_item  %>
      <%  @id = item.food_item.id %>
    <% end %>
      <h3>Total: <%= number_to_currency(@cart.total_price) %></h3>
      <% if !@cart.line_items.empty? %>
        <% if user_signed_in? %>
          <%= button_to 'Empty Cart', @cart, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-info my-4" %>
          <%= link_to "Checkout", payment_path(food_id: @id), class: "btn btn-warning", method: :post %>
        <% end %>
      <% else %>
        <p class="lead">Your cart is currently empty, please continue to shop</p>
    <% end %>
  </div>
</section>