src/home-made-meal/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#hero'
  get '/home/show/:id', to: 'home#show', as: 'show'
  get '/home/index', to: 'home#index', as: 'index'
  get '/home/about', to: 'home#about', as: 'about'
  get '/home/admin', to: 'home#admin', as: 'admin'
  devise_scope :user do
    get "/login", :to => "devise/sessions#new" # Add a custom sign in route for user sign in
    delete "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
    get "/sign_up", :to => "devise/registrations#new" # Add a Custom Route for Registrations
    devise_for :user
  end
  resources :profiles 
  resources :food_items do
    resources :comments
  end
  resources :line_items
  resources :carts
  resources :reviews
  post "payment/index", to: "payment#create", as: "payment"
  get 'payment/cancel', to: 'payment#cancel', as: 'payment_cancel'
  get 'payment/success', to: 'payment#success', as: 'payment_success'
end

src/home-made-meal/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :cart
  # to get the total price of the food item if its more than one we need to multiply the food item price to the quantity of the food item 
  def total_price
    food_item.price * quantity
  end
end

src/home-made-meal/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]
  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    # here we use the param object to get the :food_item_id parameter from the current request 
    food_item = FoodItem.find(params[:food_item_id])
    # here we use @cart to make reletion between line_item and food_item to biuld a food item 
    @line_item = @cart.add_food_item(food_item)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to index_path, notice: "The item has been added to your cart." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @line_item.cart, notice: "Item has been removed" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:food_item_id)
    end
end

src/home-made-meal/app/helpers/line_items_helper.rb
module LineItemsHelper
end

src/home-made-meal/app/views/line_items/_form.html.erb
<%= simple_form_for(@line_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :food_item %>
    <%= f.association :cart %>
  </div>  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

src/home-made-meal/app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

src/home-made-meal/app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Food item</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.food_item_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Line Item', new_line_item_path %>

src/home-made-meal/app/views/line_items/new.html.erb
<div class="container">
  <h1>New Line Item</h1>

  <%= render 'form', line_item: @line_item %>

  <%= link_to 'Back', line_items_path %>
</div>

src/home-made-meal/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food item:</strong>
  <%= @line_item.food_item_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>
<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>