src/home-made-meal/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#hero'
  get '/home/show/:id', to: 'home#show', as: 'show'
  get '/home/index', to: 'home#index', as: 'index'
  get '/home/about', to: 'home#about', as: 'about'
  get '/home/admin', to: 'home#admin', as: 'admin'
  devise_scope :user do
    get "/login", :to => "devise/sessions#new" # Add a custom sign in route for user sign in
    delete "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
    get "/sign_up", :to => "devise/registrations#new" # Add a Custom Route for Registrations
    devise_for :user
  end
  resources :profiles 
  resources :food_items do
    resources :comments
  end
  resources :line_items
  resources :carts
  resources :reviews
  post "payment/index", to: "payment#create", as: "payment"
  get 'payment/cancel', to: 'payment#cancel', as: 'payment_cancel'
  get 'payment/success', to: 'payment#success', as: 'payment_success'
end

src/home-made-meal/app/models/food_item.rb
class FoodItem < ApplicationRecord
  # profile belongs to the fooditem and profile is a foreign key in the fooditem table
  belongs_to :profile
  # food item belong to the buyer with profile, but for the user it will be optional to be a buyer
  belongs_to :buyer, class_name: "Profile", optional: true
# food item also belongs ot the seller, but for the seller in order to create food item list, the seller has to exist buy havinfg an account and creating a profile
  belongs_to :seller, class_name: "Profile"
  has_many :line_items, dependent: :destroy
  before_destroy :ensure_not_referenced_by_any_line_item
  # using enum to have a differnt type of food or diet, and useing select in the form for the food item 
  # this is for uploading an image, this will tell that we have many image to upload, we pass the attribute as a params in food item controller to be able for uploading the image, it can have multiple image for every food item, 
  has_many_attached :images, dependent: :destroy
  has_many :comments
  validates :name, presence: true, length: { minimum: 2 }
  validates :description, presence: true, length: { minimum: 2 }
  validates :price, numericality: true
  private 
    def ensure_not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line Items present')
        throw :abort
      end
    end
end

src/home-made-meal/app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: %i[ show edit update destroy ]
  # if user in not loged in user only can have access to the index and show page, nothing else
  before_action :authenticate_user!, except: [:index, :show]
  # GET /food_items or /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1 or /food_items/1.json
  def show
    if params[:check] == "success"
      @food_item.buyer_id = current_user.profile.id 
      @food_item.save
    end    
  end

  # GET /food_items/new
  def new
    # in the new action we check if the user is signed in and if the user has created profile it should take use to the new fooditem page to create a new food for sell, if user doesn't have a profile it will take use to the new profile to create a profile and then it will take use to new fooditem, and if the user hasn't sifned in or create an account it will take the user to sign up page for singing up first 
    if user_signed_in?
      if current_user.profile
        @food_item = FoodItem.new
      else 
        new_profile_path
      end
        sign_up_path
    end
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items or /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)
    # once the profile created we can assign the seller_id to the current_user.profile.id because it has passed as an attribute in the table and need to be assign from back-end
    @food_item.seller_id = current_user.profile.id
    # assign the food_item.profile_id the currernt_user.id 
    @food_item.profile_id = current_user.id

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: "Food item was successfully created." }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1 or /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: "Food item was successfully updated." }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1 or /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: "Food item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end
    
    # images attribute has been added as a params to allow the multiple images to be added in the food_item table 
    def food_item_params
      params.require(:food_item).permit(:name, :description, :availability, :food_type, :price, :buyer_id, :seller_id, :profile_id, :sales_quantity, images: [])
    end
end

src/home-made-meal/app/helpers/food_items_helper.rb
module FoodItemsHelper
end

src/home-made-meal/app/views/food_items/_form.html.erb
<% if current_user && current_user.profile  %>
  <%= simple_form_for(@food_item) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :availability %>
      <%= f.select :food_type, collection: [ "Carnivore", "Vegeterian", "Vegan"] %>
      <%= f.input :price %>
      <%= f.file_field :images, accept: "image/png, image/jpg, image/jpeg", multiple: true, class: "my-1"  %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-success my-3"  %>
    </div>
  <% end %>
<% end %>

src/home-made-meal/app/views/food_items/edit.html.erb
<div class="container">
  <h1>Editing Food Item</h1>

  <%= render 'form', food_item: @food_item %>

  <%= link_to 'Show', @food_item, class: "btn btn-primary" %> 
  <%= link_to 'Back', food_items_path, class: "btn btn-dark" %>
</div>

src/home-made-meal/app/views/food_items/index.html.erb
<section class="py-5 text-center">
  <div class="container">
    <h1>Details of items for sale</h1>
    <div class="row">
      <% @food_items.each do |food_item| %>
    <% if current_user && current_user.profile && (current_user.profile.id == food_item.seller_id) %>
      <div class="col-lg-4 g-3">
        <ul class="list-group">
          <li class="list-group-item">Name: <%= food_item.name %></li>
          <li class="list-group-item">Description: <%= food_item.description %></li>
          <li class="list-group-item">Availability: <%= food_item.availability %></li>
          <li class="list-group-item">Food type: <%= food_item.food_type %></li>
          <li class="list-group-item">Price: <%= number_to_currency(food_item.price) %></li>
          <li class="list-group-item">Buyer Id:<%= food_item.buyer_id %></li>
          <li class="list-group-item">Seller Id:<%= food_item.seller_id %></li>
          <li class="list-group-item">Seller: <%= food_item.profile.username %></li>
          <li class="list-group-item">Sold quantity: <%= food_item.sales_quantity %></li>
          <li class="list-group-item"><%= link_to 'Show', food_item, class: "btn btn-success" %></li>
          <li class="list-group-item"><% if current_user && current_user.profile && (current_user.profile.id == food_item.seller.id) %>
              <td><%= link_to 'Edit', edit_food_item_path(food_item), class: "btn btn-primary" %></td>
              <td><%= link_to 'Destroy', food_item, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %></li>
        </ul>
      </div>
  <% end %>
      <% end %>
      <div></div>
    </div>
  <%= link_to 'New Food Item', new_food_item_path, class: "btn btn-primary mt-3" %>
  </div>
</section>

src/home-made-meal/app/views/food_items/new.html.erb
<div class="container">
  <h1>New Food Item</h1>

  <%= render 'form', food_item: @food_item %>

  <%= link_to 'Back', food_items_path, class: "btn btn-dark" %>
</div>

src/home-made-meal/app/views/food_items/show.html.erb
<div class="container">
  <div class="row my-5 justify-content-between">
    <div class="col">
      <ul class="list-group">
        <li class="list-group-item">Name: <%= @food_item.name %></li>
        <li class="list-group-item">Description: <%= @food_item.description %></li>
        <li class="list-group-item">Availability: <%= @food_item.availability %></li>
          <li class="list-group-item">Food type: <%= @food_item.food_type %></li>
        <li class="list-group-item">Price: <%= number_to_currency(@food_item.price) %></li>
        <li class="list-group-item">Seller: <%= @food_item.profile.username %></li>
    </div>
    <div class="col">
    <% if @food_item.images.attached? %>
      <%= image_tag @food_item.images.first, class: "show-img" %>
    <% end %>
    </div>
  </div>
  <%# if the current user and current_user profile the same as currernt user profile id == @food_item seller id , current user will have a acees to the edit button %>
  <% if current_user && current_user.profile && (current_user.profile.id == @food_item.seller.id) %>
    <%= link_to 'Edit', edit_food_item_path(@food_item), class: "btn btn-primary my-2" %> 
    <%= link_to 'Back', food_items_path, class: "btn btn-primary my-2"%>
  <% end %>
  <%# else if the current user is no seller and if the cart include the item for buying it will show the add to current button if the current user exist and also has a pofile and once it add to the shopping cart it will show the msg to the user that the item has been added and back to shopping button will display  %>
</div>