src/home-made-meal/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#hero'
  get '/home/show/:id', to: 'home#show', as: 'show'
  get '/home/index', to: 'home#index', as: 'index'
  get '/home/about', to: 'home#about', as: 'about'
  get '/home/admin', to: 'home#admin', as: 'admin'
  devise_scope :user do
    get "/login", :to => "devise/sessions#new" # Add a custom sign in route for user sign in
    delete "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
    get "/sign_up", :to => "devise/registrations#new" # Add a Custom Route for Registrations
    devise_for :user
  end
  resources :profiles 
  resources :food_items do
    resources :comments
  end
  resources :line_items
  resources :carts
  resources :reviews
  post "payment/index", to: "payment#create", as: "payment"
  get 'payment/cancel', to: 'payment#cancel', as: 'payment_cancel'
  get 'payment/success', to: 'payment#success', as: 'payment_success'
end

src/home-made-meal/app/views/shared/_alert.html.erb
<% if notice %>
  <div class="alert alert-warning" role="alert">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>

src/home-made-meal/app/views/shared/_footer.html.erb
<footer class="footer-page mt-5 bg-orange">
  <div class="container">
    <p class="footer-text text-center text-light pt-3">Copyrights 2021 &copy;, <span class="text-dark">YourPlate</span></p>
  </div>
</footer>

src/home-made-meal/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-orange navbar-light py-3 ">
  <div class="container">
    <h1><a href="/" class="navbar-brand text-dark">YourPlate</a></h1>
    <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
    <span class="navbar-toggler-icon "></span>
    </button>
    <div class="collapse navbar-collapse" id="navmenu">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to  index_path, class: "nav-link text-light" do %>
        <i class="bi bi-house fa-2x"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to cart_path(@cart), class: "nav-link text-light" do %>
            <span class="text-light"><i class="bi bi-cart fa-2x"></i><%= cart_count_items %></span>
        <% end %>
      </li>
      <% if current_user && current_user.profile %>
        <li class="nav-item">
          <%= link_to edit_profile_path(current_user.profile), class: "nav-link text-light" do %>
            <i class="bi bi-person fa-2x"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
      <ul class="navbar-nav ms-auto text-light mt-1">
      <li class="nav-item"><%= link_to "Our Story", about_path, class: "nav-link text-light "%></li>
      <% if has_role?(:admin) %>
        <li class="nav-item">
          <%= link_to "Admin", admin_path, class: "nav-link text-light"%>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Sell food", new_food_item_path, class: "nav-link text-light"%>
      </li>
      <li class="nav-item">
    <% if user_signed_in? %>
      <%= link_to "logout", logout_path, class: "nav-link text-light", method: :delete%>
      </li>
        <li class="nav-item">
          <%= link_to "Dashboard", food_items_path, class: 'nav-link text-light'%>
        </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign in", login_path(user_type: "returning_user"), class: "nav-link text-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "Buy food", sign_up_path(user_type: "buyer"), class: "nav-link text-light"%>
      </li>
    <% end %>
      </ul>
    </div>

  </div>
</nav>